env:
  browser: true
  es2021: true

extends:
  - hardcore
  - hardcore/react
  - hardcore/react-performance
  - hardcore/ts

overrides:
  - files:
      - "**/*.tsx"
    rules:
      "total-functions/no-unsafe-readonly-mutable-assignment": "off"
      "func-style": "off"
      "react/function-component-definition": "off"
  - files:
      - "cypress/**"
    rules:
      "import/unambiguous": "off"

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
  tsconfigRootDir: .

settings:
  react:
    version: detect

rules:
  "import/no-unused-modules": "off"
