version: "3.8"
name: cypress-visual-regression
services:
  base-service:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile

    volumes:
      - ../:/app
      - node-modules:/app/node_modules

volumes:
  node-modules:
